[package]
name = "hashmap"
version = "0.1.0"
edition = "2021"
authors = ["Alexey Demyanchuk <alexeydemyanchuk@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
